---
## Galaxy Roles Needed
#  arista.eos-interfaces, arista.eos-bridging, arista.eos-bgp
#  arista.eos-ipv4, arista.eos-virtual-router, arista.eos-vxlan
- name: Provision Arista for Nutanix Demo
  hosts: demo
  gather_facts: no
  connection: local
  roles:
    - arista.eos-system
    - arista.eos-interfaces
    - arista.eos-bridging
    - arista.eos-ipv4
    - arista.eos-virtual-router
    - arista.eos-bgp
    - arista.eos-vxlan
